# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10m-qGCm5Bbpf44ml_4g0WavFVaidM4Fm
"""

# config.py

import os

# Your Discord Bot Token
# For security, you can store this as an environment variable and retrieve it with os.getenv()
# Replace 'YOUR_BOT_TOKEN_HERE' with your actual token.
BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"

# IMPORTANT:
# You must enable the "Server Members" and "Message Content" intents in your bot's
# settings on the Discord Developer Portal for many of these commands to work.

# Discord Channel and Role IDs
ROLE_ID = 1399540002752561265
LOG_CHANNEL_ID = 1399544241322987580
TICKET_CATEGORY_ID = 1400176441819402321
OWNER_ID = 1399540003192832091
UPDATE_CHANNEL_ID = 1399540003989880920
ANONYMOUS_CHANNEL_ID = 1400261649499160636
SUGGESTION_CHANNEL_ID = 1399540003989880918

# Channels where images/files must be spoilers
SPOILER_CHECK_CHANNELS = [
    1399540004270772325,
    1399540004467773484
]

# Roles and Emojis for Reaction Roles
COLOR_ROLES = {
    "maroon": "🔴",
    "my melody pink": "💖",
    "kuromi purple": "🟪",
    "ice blue": "🧊",
    "angelic yellow": "🟡",
    "ladybug red": "🐞",
    "carrot": "🥕",
    "mint green": "🍃",
    "chocy brown": "🍫",
    "baby blue": "?",
    "grape purple": "🍇",
    "pastel purple": "🌸",
    "pitch black": "⚫",
    "pearly white": "⚪",
}

LITTLE_AGE_ROLES = {
    "0-2": "🍼",
    "3-5": "🧮",
    "6-8": "🎨",
    "7+": "🎒",
}

GENDER_ROLES = {
    "female": "👩",
    "male": "👨",
    "nonbinary": "✨",
    "genderfluid": "🌊",
    "she / her": "👩",
    "he / him": "👨",
    "she / they": "👩",
    "he / they": "👨",
    "they / them": "👤",
}

REAL_AGE_ROLES = {
    "11 - 12": "🔢",
    "13 - 15": "🔢",
    "16 - 17": "🔞",
}

OTHER_ROLES = {
    "Caregiver": "🤝",
    "Little": "👶"
}

# The actual content of the introduction template as a string
INTRO_TEMPLATE_TEXT = """
Name: `Your Name Here`
Age: `Your Age Here`
Pro-Nouns: `Your Pronouns Here`
Gender: `Your Gender Here`
Likes: `Things you like`
Dislikes: `Things you dislike`
DM Status: `Open, Ask, or Closed`
Little info abt me: `A short bio about yourself`
"""