# -*- coding: utf-8 -*-
"""cogs/__init__.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0XNK4vSD5K1dS9d7j9zJRs7iTvi6-nu
"""

# cogs/__init__.py
# This file makes the "cogs" directory a Python package.